name: "Mellonee's Kitchen"
favicon: null
layout_spectrum: 0.9361084902193397
typography_spectrum: 0.9406432022806257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#2b3f34'
    - '#989eb6'
    - '#ac3c6c'
    - '#d0d1d3'
  brandStrength: 0.7812980217859149
  lightness: 0
  saturation: 0.05428274138830602
  rhythmicContrast: 0.5934464980382472
purpose: []
